FROM hexpm/elixir:1.15.7-erlang-26.2-alpine-3.18.4

USER root

RUN apk update \
  && apk add --no-cache \
    # Will install chromium 119.0.6045.159-r0 & ghostscript 10.02.0
    chromium \
    ghostscript \
    # for verapdf & ZUV
    openjdk11-jre \
    # for pdftotext & friends
    poppler-utils \
    # for identifying images
    imagemagick \
    # for 'kill'
    procps \
    # temporary for installation below
    wget \
    unzip \
    # GNU tar needed by actions/cache
    tar

RUN mkdir /opt/verapdf
WORKDIR /opt/verapdf
RUN wget http://downloads.verapdf.org/rel/verapdf-installer.zip \
  && unzip verapdf-installer.zip \
  && mv verapdf-greenfield* verapdf-greenfield \
  && chmod +x verapdf-greenfield/verapdf-install
COPY .github/docker/auto-install.xml /opt/verapdf/verapdf-greenfield
RUN ./verapdf-greenfield/verapdf-install auto-install.xml

WORKDIR /opt/zuv
RUN wget https://github.com/ZUGFeRD/ZUV/releases/download/v0.8.3/ZUV-0.8.3.jar
ENV ZUV_JAR /opt/zuv/ZUV-0.8.3.jar

RUN apk del \
    wget \
    unzip \
	&& rm -rf /var/lib/apt/lists/*
