name: Test
on: [pull_request]
jobs:
  test:
    name: Run '${{ matrix.mix_env }}' tests on ${{ matrix.image }}
    strategy:
      matrix:
        mix_env: ['test', 'integration']
        image: ['maltoe/chromic-pdf-primary:0.0.9']
    env:
      MIX_ENV: ${{ matrix.mix_env }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      options: --privileged --user 1001
    steps:
      - uses: actions/checkout@v3
      - name: Dependencies cache
        id: deps-cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.mix_env }}-deps-v1-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Build artifacts cache
        id: build-cache
        uses: actions/cache@v3
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.mix_env }}-build-v1-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile
      - run: mix chromic_pdf.warm_up
      - run: mix test
